apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::371621927995:role/eksctl-eksctl-demomay-nodegroup-n-NodeInstanceRole-6Y3YM0ODELE3
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::371621927995:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-02T15:22:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1279"
  uid: 08b7db63-5044-4596-b4a2-3420063200de
